;Custom_OpenClash_Rules
;全分组防 DNS 泄漏订阅转换模板
;作者：https://github.com/Aethersailor
;项目地址：https://github.com/Aethersailor/Custom_OpenClash_Rules
;基于 ACL4SSR 模板魔改而来，感谢原作者！
;<必须>搭配本项目配套教程，实现最佳化的 OpenClash 使用效果！
;教程：https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88
;有问题可提 issue，或者加入本项目 Telegram 群组进行讨论
;Telegram 群组：https://t.me/custom_openclash_rules_group
;Telegram 通知频道：https://t.me/custom_openclash_rules
;建议加入通知频道或群组，谨防失联

[custom]
;设置规则标志位
;以下规则，按照从上往下的顺序遍历，优先命中上位规则，规则重复无影响
;修改顺序会影响分流效果

;本地地址和域名直连
ruleset=🎯 全球直连,[]GEOSITE,private
ruleset=🎯 全球直连,[]GEOIP,private,no-resolve
;本项目收录的直连域名规则
ruleset=🎯 全球直连,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.yaml,28800
ruleset=🎯 全球直连,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800
ruleset=🎯 全球直连,https://raw.githubusercontent.com/orthwang/w-j-h/refs/heads/main/direct.list
;;本项目收录的代理规则
ruleset=🚀 手动选择,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Domain.yaml,28800
ruleset=🚀 手动选择,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Classical_IP.yaml,28800
;谷歌在国内可用的域名直连
ruleset=🎯 全球直连,[]GEOSITE,google-cn
;国内游戏域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-games@cn
;Steam 下载 CDN 直连
ruleset=🎯 全球直连,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical.yaml,28800
;各大游戏平台下载域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-game-platforms-download
;BT Tracker 相关域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker
ruleset=🌐 Meta AI,https://raw.githubusercontent.com/orthwang/w-j-h/refs/heads/main/MetaAI.list
ruleset=📺 Peacock,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Peacock/Peacock.yaml,28800
ruleset=📺 Peacock,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sling/Sling.yaml,28800
ruleset=📺 Peacock,https://raw.githubusercontent.com/orthwang/w-j-h/refs/heads/main/us.list
;即时通讯包括了 Telegram/WhatsApp/Line 等海外主流即时通讯软件域名
ruleset=☁️ 即时通讯,[]GEOSITE,category-communication
;社交媒体包括了 Twitter(X)/Facebook/Instagram 等海外主流社交媒体
ruleset=🌐 社交媒体,[]GEOSITE,category-social-media-!cn
ruleset=🤖 ChatGPT,[]GEOSITE,openai
ruleset=💾 OneDrive,[]GEOSITE,onedrive
ruleset=🤖 Copilot,[]GEOSITE,bing
ruleset=🤖 AI服务,[]GEOSITE,category-ai-!cn
ruleset=🚀 GitHub,[]GEOSITE,github
;测速工具包括 SpeedTest 等主流测速工具域名
ruleset=🚀 测速工具,[]GEOSITE,category-speedtest
ruleset=🎮 Steam,[]GEOSITE,steam
ruleset=📹 YouTube,[]GEOSITE,youtube
ruleset=🎥 AppleTV+,[]GEOSITE,apple-tvplus
ruleset=🍎 苹果服务,[]GEOSITE,apple
ruleset=Ⓜ️ 微软服务,[]GEOSITE,microsoft
ruleset=📢 谷歌FCM,[]GEOSITE,googlefcm
ruleset=🇬 谷歌服务,[]GEOSITE,google
ruleset=🎶 TikTok,[]GEOSITE,tiktok
ruleset=🎥 Netflix,[]GEOSITE,netflix
ruleset=🎥 DisneyPlus,[]GEOSITE,disney
ruleset=🎥 HBO,[]GEOSITE,hbo
ruleset=🎥 PrimeVideo,[]GEOSITE,primevideo

ruleset=📺 BBC,[]GEOSITE,BBC
ruleset=📺 Hamivideo,[]GEOSITE,HamiVideo

;Emby 包括主流 Emby 服务相关域名
ruleset=🌐 🇯🇵 Japan,https://raw.githubusercontent.com/orthwang/w-j-h/refs/heads/main/JP.list
ruleset=🎥 Emby,[]GEOSITE,category-emby
ruleset=🎻 Spotify,[]GEOSITE,spotify
ruleset=📺 Hamivideo,[]GEOSITE,bahamut
ruleset=🎮 游戏平台,[]GEOSITE,category-games
ruleset=🌎 国外媒体,[]GEOSITE,category-entertainment
ruleset=⏬ PT站点,[]GEOSITE,category-pt
ruleset=💳 PayPal,[]GEOSITE,paypal
ruleset=🛒 国外电商,[]GEOSITE,category-ecommerce
ruleset=🚀 手动选择,[]GEOSITE,gfw
ruleset=☁️ 即时通讯,[]GEOIP,telegram,no-resolve
ruleset=🌐 社交媒体,[]GEOIP,twitter,no-resolve
ruleset=🌐 社交媒体,[]GEOIP,facebook,no-resolve
ruleset=🇬 谷歌服务,[]GEOIP,google,no-resolve
ruleset=🎥 Netflix,[]GEOIP,netflix,no-resolve
;由于 OpenClash 使用的大陆白名单收录不全，此处留有 geosite:cn 作为国内域名兜底
ruleset=🎯 全球直连,[]GEOSITE,cn
;由于 OpenClash 使用的大陆白名单收录不全，此处留有 geoip:cn 作为国内 IP 兜底
ruleset=🎯 全球直连,[]GEOIP,cn,no-resolve
;以上兜底规则会根据实际情况随时取消
;PT/BT 优化开启会使 80/443 以外端口的流量直连
ruleset=🔀 非标端口,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml,28800
;国内冷门域名会命中漏网之鱼，如影响使用，请设置漏网之鱼直连
;漏网之鱼直连时，无法通过 DNS 泄露测试，但是并不存在泄露
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位结束

;设置节点分组标志位
;节点地区分组参考本项目推荐机场而设立
custom_proxy_group=🚀 手动选择`select`[]🇭🇰 HongKong`[]🇺🇸 USA`[]🇯🇵 Japan`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`.*
custom_proxy_group=🇺🇸 USA`select`(🇺🇸|美|US|United States|UnitedStates|USA)
custom_proxy_group=🇭🇰 HongKong`select`(🇭🇰|港|HK|hk|Hong Kong|HongKong|hongkong)
custom_proxy_group=🇯🇵 Japan`select`(🇯🇵|日本|JP)
custom_proxy_group=📹 YouTube`select`[]🇭🇰 HongKong`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇺🇸 USA`[]🇺🇸 美国节点`[]🇼🇸 台湾节点`.*
custom_proxy_group=🎥 Netflix`select`[]🇭🇰 HongKong`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇺🇸 USA`[]🇺🇸 美国节点`[]🇼🇸 台湾节点`.*
custom_proxy_group=🎥 DisneyPlus`select`[]🇭🇰 HongKong`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇺🇸 USA`[]🇺🇸 美国节点`[]🇼🇸 台湾节点`.*
custom_proxy_group=🎥 HBO`select`[]🇭🇰 HongKong`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇺🇸 USA`[]🇺🇸 美国节点`[]🇼🇸 台湾节点`.*
custom_proxy_group=🎥 PrimeVideo`select`[]🇭🇰 HongKong`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🇺🇸 USA`[]🇺🇸 美国节点`.*
custom_proxy_group=🌐 Meta AI`select`[]🇺🇸 USA`[]🚀 手动选择`[]🇺🇸 美国节点`(美|US|United States|UnitedStates|USA)
custom_proxy_group=📺 Peacock`select`[]🇺🇸 USA`[]🚀 手动选择`[]🇺🇸 美国节点`(美|US|United States|UnitedStates|USA)
custom_proxy_group=📢 谷歌FCM`select`[]🚀 手动选择`[]🇺🇸 USA`[]🇭🇰 HongKong`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=🇬 谷歌服务`select`[]🚀 手动选择`[]🇺🇸 USA`[]🇭🇰 HongKong`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=🤖 AI服务`select`[]🚀 手动选择`[]🇺🇸 USA`[]🇭🇰 HongKong`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`.*
custom_proxy_group=🤖 ChatGPT`select`[]🚀 手动选择`[]🇭🇰 HongKong`[]🇺🇸 USA`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`.*
custom_proxy_group=🤖 Copilot`select`[]🚀 手动选择`[]🇭🇰 HongKong`[]🇺🇸 USA`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=🎻 Spotify`select`[]🚀 手动选择`[]🇭🇰 HongKong`[]🇺🇸 USA`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=🚀 GitHub`select`[]🚀 手动选择`[]🇭🇰 HongKong`[]🇺🇸 USA`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🎯 全球直连
custom_proxy_group=🎶 TikTok`select`[]🚀 手动选择`[]🇭🇰 HongKong`[]🇭🇰 香港节点`[]🇺🇸 USA`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=🌎 国外媒体`select`[]🚀 手动选择`[]🇺🇸 USA`[]🇭🇰 HongKong`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=☁️ 即时通讯`select`[]🚀 手动选择`[]🇭🇰 HongKong`[]🇺🇸 USA`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点
custom_proxy_group=🌐 社交媒体`select`[]🚀 手动选择`[]🇭🇰 HongKong`[]🇺🇸 USA`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`.*
custom_proxy_group=🛒 国外电商`select`[]🚀 手动选择`[]🇺🇸 USA`[]🇭🇰 HongKong`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=💳 PayPal`select`[]🚀 手动选择`[]🇺🇸 USA`[]🇭🇰 HongKong`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=📺 BBC`select`[]🇬🇧 英国节点`(英国|UK|Great Britain|英|United Kingdom)
custom_proxy_group=📺 Hamivideo`select`[]🇼🇸 台湾节点`(台|TW|Taiwan)
custom_proxy_group=🎥 AppleTV+`select`[]🚀 手动选择`[]🇭🇰 HongKong`[]🇺🇸 USA`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=🎥 Emby`select`[]🎯 全球直连`[]🇭🇰 HongKong`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇼🇸 台湾节点`[]🚀 手动选择`.*
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🚀 手动选择
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🚀 手动选择
custom_proxy_group=💾 OneDrive`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🚀 手动选择
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🚀 手动选择
custom_proxy_group=🎮 Steam`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🚀 手动选择`.*
custom_proxy_group=⏬ PT站点`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇼🇸 台湾节点`[]🚀 手动选择`.*
custom_proxy_group=🚀 测速工具`select`[]🎯 全球直连`[]🇺🇸 USA`[]🇭🇰 HongKong`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🚀 手动选择`.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 手动选择`[]🇺🇸 USA`[]🇭🇰 HongKong`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🎯 全球直连`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 遵循规则`select`[]🐟 漏网之鱼
custom_proxy_group=🔀 非标端口`select`[]🐟 遵循规则`[]🎯 全球直连
custom_proxy_group=🇺🇸 美国节点`url-test`(🇺🇸|美|US|United States|UnitedStates|USA)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港节点`url-test`(🇭🇰|港|HK|hk|Hong Kong|HongKong|hongkong)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(🇯🇵|日本|JP)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新加坡|新|坡|狮城|SG|Singapore)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇼🇸 台湾节点`url-test`(台|TW|Taiwan)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国节点`url-test`(英国|UK|Great Britain|英|United Kingdom)`https://cp.cloudflare.com/generate_204`300,,50


;设置分组标志位

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true
